# Generated by Django 4.2.5 on 2023-09-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0019_user_is_parent_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerParentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uesr_id', models.CharField(max_length=100)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='elearn.learner')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearn.learner')),
            ],
        ),
    ]
