# Generated by Django 4.2.5 on 2023-09-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0020_learnerparentconnection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnerparentconnection',
            old_name='uesr_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='parent',
            name='learner_linked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elearn.learner'),
        ),
    ]
