# Generated by Django 4.2.5 on 2023-09-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0021_rename_uesr_id_learnerparentconnection_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='learner_linked',
        ),
    ]
