# Generated by Django 4.2.5 on 2023-09-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearn', '0022_remove_parent_learner_linked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerparentconnection',
            name='student',
        ),
        migrations.RemoveField(
            model_name='learnerparentconnection',
            name='user_id',
        ),
    ]
